openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
servers:
  - url: https://petstore15.swagger.io/api/v3
paths:
  /pet:
    put:
      tags:
        - pet
      summary: gUpdate an existing pet
      description: Update an existing pet by Id
      operationId: updatePet`
